name: Docker multi-arch build and push

on:
  push:
  pull_request:


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'docs/'
          doxyfile-path: 'Doxyfile'
      - name: apply custom css
        run: |
          rm ./docs/html/doxygen.css
          cp ./doxygen.css ./docs/html/doxygen.css
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
