name: Docker multi-arch build and push

on:
  push:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build tdlib
        run: |
          sudo apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake g++
          
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
          cmake --build . --target install
          cd ..
      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'docs/'
          doxyfile-path: 'Doxyfile'
      - name: apply custom css
        run: |
          sudo cp doxygen.css docs/html/doxygen.css
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
